addSbtPlugin("com.codecommit"     % "sbt-github-actions"        % "0.14.2")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.github.sbt"   % "sbt-git"                   % "2.0.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                % "5.6.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"           % "1.0.1")
addSbtPlugin("io.crashbox"        % "sbt-gpg"                   % "0.2.1")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"          % "1.1.0")
