addSbtPlugin("com.codecommit"     % "sbt-github-actions" % "0.9.5")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"            % "1.0.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"         % "5.6.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"    % "0.8.1")
addSbtPlugin("io.crashbox"        % "sbt-gpg"            % "0.2.0")
addSbtPlugin("ch.epfl.lamp"       % "sbt-dotty"          % "0.4.5")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"   % "1.0.0")
